spring.application.name=url_shortner
spring.datasource.url=jdbc:postgresql://localhost:5432/Url_Shortner
spring.datasource.username=postgres
spring.datasource.password=Djjeena@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=redis-13870.crce286.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=13870
spring.cache.type=redis
spring.data.redis.password=TWGLmfEAAYCC7KXLa8iZoFO97wIEsiCY
